### ISSUE TITLE
New release with req ~> 0.5 ?

### ISSUE THREAD

**Issue by yasuf** [3zcurdia/chroma#32]
Hey!

Wondering if there will be a release with `req ~> 0.5`, I'm running into an error when attempting to add this dependency to a `phoenix` project when doing `mix deps.get`

```
Resolution completed in 0.151s
Because the lock depends on swoosh 1.16.9 which depends on req ~> 0.5 or ~> 1.0, the lock requires req ~> 0.5 or ~> 1.0.
And because every version of chroma depends on req ~> 0.3.11, the lock is incompatible with chroma.
And because your app depends on the lock, no version of chroma is allowed.
So, because your app depends on chroma ~> 0.1.0, version solving failed.
** (Mix) Hex dependency resolution failed
```

**Comment by yasuf** [comment]
I was able to work around this by defining the dependency from the github repo:
```
      {:chroma, git: "https://github.com/3zcurdia/chroma.git"}
```
But would be nice to get the new release regardless so that it's more stable!

**Comment by 3zcurdia** [comment]
Thanks @yasuf I'll push the patch

**Comment by 3zcurdia** [comment]
Just released https://github.com/3zcurdia/chroma/releases/tag/v0.1.3
